name: Auto Update Astro GO Playlist

on:
  schedule:
    # Mengarahkan robot berjalan secara automatik setiap 3 jam
    - cron: '0 */3 * * *'
  workflow_dispatch: # Menyediakan butang untuk anda jalankan secara manual bila-bila masa

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kod Laman (Checkout)
        uses: actions/checkout@v4

      - name: Sediakan Persekitaran Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Pasang Library Tambahan
        run: |
          pip install requests

      - name: Jalankan Skrip Penjana Playlist
        env:
          # Menyambungkan skrip Python dengan GitHub Secrets yang selamat
          ASTRO_USER: ${{ secrets.ASTRO_GO_USERNAME }}
          ASTRO_PASS: ${{ secrets.ASTRO_GO_PASSWORD }}
        run: python fetch_astro.py

      - name: Simpan Fail M3U Terkini ke Repository
        run: |
          git config --global user.name "Astro-Bot"
          git config --global user.email "bot@github.com"
          git add playlist.m3u
          
          # Hanya commit dan push sekiranya ada perubahan pada kandungan token playlist
          if git diff --staged --quiet; then
            echo "Tiada perubahan dikesan pada playlist."
          else
            git commit -m "Kemas kini token playlist Astro GO [Skip CI]"
            git push
          fi
